name = "frevector-com"
main = "sitemap-sync-worker.js"
compatibility_date = "2026-01-01"

[triggers]
crons = ["0 * * * *"] # Her saat başı çalışır

[[r2_buckets]]
binding = "VECTOR_ASSETS"
bucket_name = "vector-assets"
